"""Fix UserData.

Revision ID: 41befb6bd76e
Revises: ee00dafcf801
Create Date: 2019-03-25 16:08:22.446711

"""

# revision identifiers, used by Alembic.
revision = '41befb6bd76e'
down_revision = 'ee00dafcf801'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
