"""Add new table UserData.

Revision ID: ee00dafcf801
Revises: 51f5ccfba190
Create Date: 2019-03-25 12:00:48.090329

"""

# revision identifiers, used by Alembic.
revision = 'ee00dafcf801'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_timestamp'), 'user_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_data_timestamp'), table_name='user_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
